ACCOUNTABLE:
  NFT_PER_ACCOUNT_LIMIT: 3

APRIORI:
  AMOUNT_TO_STAKE:
  - 0.0001
  - 0.0003

BIMA:
  LEND: true
  PERCENT_OF_BALANCE_TO_LEND:
  - 20.0
  - 30.0

DEMASK:
  MAX_AMOUNT_FOR_EACH_ACCOUNT:
  - 1
  - 3

DISPERSE:
  MIN_BALANCE_FOR_DISPERSE:
  - 0.2
  - 0.5

EXCHANGES:
  apiKey: ''
  name: OKX
  passphrase: ''
  secretKey: ''
  withdrawals:
  - currency: ETH
    networks:
    - Arbitrum
    - Base
    - Optimism
    min_amount: 0.0003
    max_amount: 0.0004
    max_balance: 0.005
    wait_for_funds: true
    max_wait_time: 99999
    retries: 3

FAUCET:
  CAPSOLVER_API_KEY: CAP-

FLOW:
  NUMBER_OF_SWAPS:
  - 1
  - 3
  PERCENT_OF_BALANCE_TO_SWAP:
  - 10
  - 15

GASZIP:
  AMOUNT_TO_REFUEL:
  - 0.0001
  - 0.00015
  BRIDGE_ALL: false
  BRIDGE_ALL_MAX_AMOUNT: 0.0002
  MAX_WAIT_TIME: 999999
  MINIMUM_BALANCE_TO_REFUEL: 0.5
  NETWORKS_TO_REFUEL_FROM:
  - Arbitrum
  - Base
  - Optimism
  WAIT_FOR_FUNDS_TO_ARRIVE: true

KINTSU:
  AMOUNT_TO_STAKE:
  - 0.01
  - 0.02

LILCHOGSTARS:
  MAX_AMOUNT_FOR_EACH_ACCOUNT:
  - 1
  - 3

MAGICEDEN:
  NFT_CONTRACTS:
  - '0x8f9571324a98D4c78B6530C97487D34607CDf244'
  - '0xfd3B54Bd826cea09d15e87F95A869ECF3E462f92'
  - '0xf9c6fCD5C8eF350Df31b39e9E7308D521add1a94'
  - '0xB2eA0ff3ad4134367FB7dc75D48b3493E5A09C81'
  - '0xa951Bb8126d81d6Aeaf73Cc335fC7b7444dF9520'
  - '0x690CfACdc08dC7DA79736906CD506890D6ca224A'


MAGMA:
  AMOUNT_TO_STAKE:
  - 0.0001
  - 0.0003

MEMEBRIDGE:
  AMOUNT_TO_REFUEL:
  - 0.0001
  - 0.00015
  BRIDGE_ALL: false
  BRIDGE_ALL_MAX_AMOUNT: 0.0002
  MAX_WAIT_TIME: 999999
  MINIMUM_BALANCE_TO_REFUEL: 0.5
  NETWORKS_TO_REFUEL_FROM:
  - Arbitrum
  - Base
  - Optimism
  WAIT_FOR_FUNDS_TO_ARRIVE: true

MONADKING:
  MAX_AMOUNT_FOR_EACH_ACCOUNT:
  - 1
  - 3

ORBITER:
  AMOUNT_TO_BRIDGE:
  - 0.1
  - 0.2
  BRIDGE_ALL: true
  MAX_WAIT_TIME: 999999999
  WAIT_FOR_FUNDS_TO_ARRIVE: true

SETTINGS:
  ACCOUNTS_RANGE:
  - 0
  - 0
  ATTEMPTS: 5
  BROWSER_PAUSE_MULTIPLIER: 1.5
  EXACT_ACCOUNTS_TO_USE: []
  PAUSE_BETWEEN_ATTEMPTS:
  - 8
  - 15
  PAUSE_BETWEEN_SWAPS:
  - 35
  - 70
  RANDOM_INITIALIZATION_PAUSE:
  - 20
  - 40
  RANDOM_PAUSE_BETWEEN_ACCOUNTS:
  - 15
  - 30
  RANDOM_PAUSE_BETWEEN_ACTIONS:
  - 35
  - 70
  TELEGRAM_BOT_TOKEN: ''
  TELEGRAM_USERS_IDS: []
  THREADS: 10

SHMONAD:
  BUY_AND_STAKE_SHMON: true
  PERCENT_OF_BALANCE_TO_SWAP:
  - 2
  - 3
  UNSTAKE_AND_SELL_SHMON: true

TESTNET_BRIDGE:
  AMOUNT_TO_REFUEL:
  - 0.0002
  - 0.0003
  MAX_WAIT_TIME: 999999
  MINIMUM_BALANCE_TO_REFUEL: 5.0
  NETWORKS_TO_REFUEL_FROM:
  - Arbitrum
  - Optimism
  WAIT_FOR_FUNDS_TO_ARRIVE: true
